from tkinter import Tk, Menu
import tkinter as tk

# Initialize main window
window = Tk()
window.minsize(width=500, height=500)
window.title("Thiraphat")



# Exit Button
window_button = tk.Button(master=window, text="Exit", command=window.destroy)
window_button.pack()

# Create Menu Bar
menuber = tk.Menu(window)
title_label =tk.Label(master=window,text="Thiraphat Auppanan",font= 20,)
title_label.pack(side="bottom")

# File Menu
file_Menu = Menu(menuber, tearoff=0)
menuber.add_cascade(label='File', menu=file_Menu, underline=0)
file_Menu.add_command(label='New Text File', accelerator="Ctrl+N")
file_Menu.add_command(label='New File ...',accelerator="Ctrl+Alt+Windows+N")
file_Menu.add_command(label='New Window' , accelerator="Ctrl+Shift+N")

sub_menu = Menu(file_Menu, tearoff=0)
sub_menus = Menu(sub_menu , tearoff=0)

sub_menus.add_cascade(label='file....')
sub_menu.add_cascade(label='New Profile ....', menu=sub_menus)
file_Menu.add_cascade(label='New Window with Profile' , menu=sub_menu)


file_Menu.add_separator()
file_Menu.add_command(label='Open file...', accelerator="Ctrl+O")
file_Menu.add_command(label='Open Folder...', accelerator="Ctrl+K Ctrl+O")
file_Menu.add_command(label='Open Workspace from File...')

sub_menu = Menu(file_Menu , tearoff=0)
sub_menu.add_cascade(label='')
file_Menu.add_cascade(label='Open Recent')
file_Menu.add_separator()
file_Menu.add_command(label='Add Folder to Workspace...')
file_Menu.add_command(label='Save Workspace As...')
file_Menu.add_command(label='Duplicate Workspace')
file_Menu.add_separator()
file_Menu.add_command(label="Save", accelerator="Ctrl+S")
file_Menu.add_command(label="Save As...", accelerator="Ctrl+Shift+S")
file_Menu.add_command(label="Save All", accelerator="Ctrl+K S")
file_Menu.add_separator()

sub_menu = Menu(file_Menu , tearoff=0)
sub_menu.add_cascade(label='Export Profile ....')

file_Menu.add_cascade(label="Share", menu=sub_menu)
file_Menu.add_separator()
file_Menu.add_command(label="Auto Save")

sub_menu = Menu(file_Menu , tearoff=0)
sub_menus = Menu(sub_menu , tearoff=0)
sub_menu.add_cascade(label='Profiles')
sub_menu.add_command(label='Settings',accelerator="Ctrl+x")
sub_menu.add_command(label='Extensions',accelerator="Ctrl+Shift+X")
sub_menu.add_command(label='Keyboard Shortcuts',accelerator="Ctrl+K Ctrl+S")
sub_menu.add_command(label='Configure Snippets')
sub_menu.add_cascade(label='Tasks')
sub_menu.add_cascade(label='Theme',menu=sub_menus)
sub_menus.add_command(label='Color Theme',accelerator="Ctrl+K Ctrl+T")
sub_menus.add_command(label='File Icon Theme')
sub_menus.add_command(label='Product Icon Theme')
sub_menu.add_separator()
sub_menu.add_cascade(label='Backup and Sync Settings...')
sub_menu.add_separator()
sub_menu.add_cascade(label='Online Services Settings')


file_Menu.add_cascade(label="Preferences" , menu=sub_menu)
file_Menu.add_separator()
file_Menu.add_command(label="Revert File")
file_Menu.add_command(label="Close Editor", accelerator="Ctrl+F4")
file_Menu.add_command(label="Close Folder", accelerator="Ctrl+K F")
file_Menu.add_command(label="Close Window", accelerator="Alt+F4")
file_Menu.add_separator()
file_Menu.add_command(label="Exit", command=exit)

# Edit Menu
edit_Menu = Menu(menuber, tearoff=0)
menuber.add_cascade(label='Edit', menu=edit_Menu, underline=0)
edit_Menu.add_command(label="Undo", accelerator="Ctrl+Z")
edit_Menu.add_command(label="Redo", accelerator="Ctrl+Y")
edit_Menu.add_separator()
edit_Menu.add_command(label="Cut", accelerator="Ctrl+X  ")
edit_Menu.add_command(label="Copy", accelerator="Ctrl+C")
edit_Menu.add_command(label="Paste", accelerator="Ctrl+V")
edit_Menu.add_separator()
edit_Menu.add_command(label="Find", accelerator="Ctrl+F")
edit_Menu.add_command(label="Replace", accelerator="Ctrl+H")
edit_Menu.add_separator()
edit_Menu.add_command(label="Find in Files", accelerator="Ctrl+Shift+F")
edit_Menu.add_command(label="Replace in Files", accelerator="Ctrl+Shift+H")
edit_Menu.add_separator()
edit_Menu.add_command(label="Toggle Line Comment", accelerator="Ctrl+/")
edit_Menu.add_command(label="Toggle Block Comment", accelerator="Shift+Alt+A")
edit_Menu.add_command(label="Emmet: Expand Abbreviation", accelerator="Tab")

# Selection Menu
selection_Menu = Menu(menuber, tearoff=0)
menuber.add_cascade(label='Selection', menu=selection_Menu, underline=0)
selection_Menu.add_command(label="Select All", accelerator="Ctrl+A")
selection_Menu.add_command(label="Expand Selection", accelerator="Shift+Alt+RightArrow")
selection_Menu.add_command(label="Shrink Selection", accelerator="Shift+Alt+LeftArrow")
selection_Menu.add_separator()
selection_Menu.add_command(label="Copy Line Up", accelerator="Shift+Alt+UpArrow")
selection_Menu.add_command(label="Copy Line Down", accelerator="Shift+Alt+DownArrow")
selection_Menu.add_command(label="Move Line Up", accelerator="Alt+UpArrow")
selection_Menu.add_command(label="Move Line Down", accelerator="Alt+DownArrow")
selection_Menu.add_command(label="Duplicate Selection")
selection_Menu.add_separator()
selection_Menu.add_command(label="Add Cursor Above", accelerator="Ctrl+Alt+UpArrow")
selection_Menu.add_command(label="Add Cursor Below", accelerator="Ctrl+Alt+DownArrow")
selection_Menu.add_command(label="Add Cursors to Line Ends", accelerator="Shift+Alt+1")
selection_Menu.add_command(label="Add Next Occurrence", accelerator="Ctrl+D")
selection_Menu.add_command(label="Add Previous Occurrence")
selection_Menu.add_command(label="Select All Occurrences", accelerator="Ctrl+Shift+L")
selection_Menu.add_separator()
selection_Menu.add_command(label="Switch to Ctrl+Click for Multi-Cursor")
selection_Menu.add_command(label="Column Selection Mode")

# View Menu
view_Menu = Menu(menuber, tearoff=0)
menuber.add_cascade(label='View', menu=view_Menu, underline=0)
view_Menu.add_command(label="Command Palette...", accelerator="Ctrl+Shift+P")
view_Menu.add_command(label="Open View...")
view_Menu.add_separator()

sub_menu = Menu(view_Menu , tearoff=0)
sub_menus = Menu(sub_menu , tearoff=0)

sub_menus.add_cascade(label='Default')
sub_menus.add_cascade(label='Top')
sub_menus.add_cascade(label='Bottom')
sub_menus.add_cascade(label='Hidden')

sub_menu.add_command(label='Full Screen',accelerator="F11")
sub_menu.add_command(label='Zen Mode',accelerator="Ctrl+KZ")
sub_menu.add_cascade(label='Centered Layout')
sub_menu.add_separator()
sub_menu.add_cascade(label='Menu Bar')
sub_menu.add_command(label='Primary Side Bar',accelerator="Ctrl+B")
sub_menu.add_command(label='Secondary Side Bar',accelerator="Ctrl+Alt+B")
sub_menu.add_cascade(label='Status Bar')
sub_menu.add_command(label='Panel',accelerator="Ctrl+J")
sub_menu.add_separator()
sub_menu.add_cascade(label='Move Primary Side Bar Right')
sub_menu.add_cascade(label='Activity Bar Position' , menu=sub_menus)

sub_menus = Menu(sub_menu , tearoff=0)
sub_menus.add_cascade(label='Top')
sub_menus.add_cascade(label='Left')
sub_menus.add_cascade(label='Right')
sub_menus.add_cascade(label='Bottom')

sub_menu.add_cascade(label='Panel Position' , menu=sub_menus)

sub_menus = Menu(sub_menu , tearoff=0)
sub_menus.add_cascade(label='Center')
sub_menus.add_cascade(label='Justify')
sub_menus.add_cascade(label='Left')
sub_menus.add_cascade(label='Right')

sub_menu.add_cascade(label='Align Panel', menu=sub_menus)

sub_menus = Menu(sub_menu , tearoff=0)
sub_menus.add_cascade(label='Multiple Tabs')
sub_menus.add_cascade(label='Single Tab')
sub_menus.add_cascade(label='Hidden')

sub_menu.add_cascade(label='Tab Bar', menu=sub_menus)

sub_menus = Menu(sub_menu , tearoff=0)
sub_menus.add_cascade(label='Tab Bar')
sub_menus.add_cascade(label='Title Bar')
sub_menus.add_cascade(label='Hidden')


sub_menu.add_cascade(label='Editor Actions Position')
sub_menu.add_separator()
sub_menu.add_cascade(label='Minimap')
sub_menu.add_cascade(label='Toggle Breadcrumbs')
sub_menu.add_cascade(label='Sticky Scroll')
sub_menu.add_cascade(label='Render Whitespace')
sub_menu.add_cascade(label='Render Control Characters')
sub_menu.add_separator()
sub_menu.add_command(label='Zoom In',accelerator="Ctrl+=")
sub_menu.add_command(label='Zoom Out',accelerator="Ctrl+-")
sub_menu.add_command(label='Reset Zoom',accelerator="Ctrl+NumPado")

view_Menu.add_cascade(label="Appearance", menu=sub_menu)

sub_menu = Menu(view_Menu , tearoff=0)
sub_menu.add_command(label='Split Up',accelerator="Ctrl+K Ctrl+\ ")
sub_menu.add_cascade(label='Split Down')
sub_menu.add_cascade(label='Split Left')
sub_menu.add_cascade(label='Split Right')
sub_menu.add_separator()
sub_menu.add_command(label='Split in Group',accelerator="Ctrl+K Ctrl+Shift+\ ")
sub_menu.add_separator()
sub_menu.add_cascade(label='Move Editor into New Window')
sub_menu.add_command(label='Copy Editor into New Window',accelerator="Ctrl+K O")
sub_menu.add_separator()
sub_menu.add_cascade(label='Single')
sub_menu.add_cascade(label='Two Columns')
sub_menu.add_cascade(label='Three Columns')
sub_menu.add_cascade(label='Two Rows')
sub_menu.add_cascade(label='Three Rows')
sub_menu.add_cascade(label='Grid (2x2')
sub_menu.add_cascade(label='Two Rows Right')
sub_menu.add_cascade(label='Two Columns Bottom')
sub_menu.add_separator()
sub_menu.add_command(label='Flip Layout',accelerator="Shift+Alt+0")

view_Menu.add_cascade(label="Editor Layout" , menu=sub_menu)

view_Menu.add_separator()
view_Menu.add_command(label="Explorer", accelerator="Ctrl+Shift+E")
view_Menu.add_command(label="Search", accelerator="Ctrl+Shift+F")
view_Menu.add_command(label="Source Control", accelerator="Ctrl+Shift+G")
view_Menu.add_command(label="Run", accelerator="Ctrl+Shift+D")
view_Menu.add_command(label="Extensions", accelerator="Ctrl+Shift+X")
view_Menu.add_command(label="Testing")
view_Menu.add_separator()
view_Menu.add_command(label="Problems", accelerator="Ctrl+Shift+M")
view_Menu.add_command(label="Output", accelerator="Ctrl+Shift+U")
view_Menu.add_command(label="Debug Console", accelerator="Ctrl+Shift+Y")
view_Menu.add_command(label="Terminal", accelerator="Ctrl+`")
view_Menu.add_separator()
view_Menu.add_command(label="Word Wrap", accelerator="Alt+Z")

# Go Menu
go_Menu = Menu(menuber, tearoff=0)
menuber.add_cascade(label='Go', menu=go_Menu, underline=0)
go_Menu.add_command(label="Back", accelerator="Alt+LeftArrow")
go_Menu.add_command(label="Forward", accelerator="Alt+RightArrow")
go_Menu.add_command(label="Last Edit Location", accelerator="Ctrl+K Ctrl+Q")
go_Menu.add_separator()

sub_menu = Menu(go_Menu , tearoff=0)
sub_menu.add_command(label='Next Editor', accelerator="Ctrl+PageDown")
sub_menu.add_command(label='Previous Editor', accelerator="Ctrl+PageUp")
sub_menu.add_separator()
sub_menu.add_cascade(label='Next Used Editor')
sub_menu.add_cascade(label='Previous Used Editor')
sub_menu.add_separator()
sub_menu.add_command(label='Next Editor in Group', accelerator="Ctrl+K Ctrl+Page Down")
sub_menu.add_command(label='Previous Editor in Group', accelerator="Ctrl+K Ctrl+PageUp")
sub_menu.add_separator()
sub_menu.add_cascade(label='Next Used Editor in Group')
sub_menu.add_cascade(label='Previous Used Editor in Group')


go_Menu.add_cascade(label="Switch Editor" , menu= sub_menu)

sub_menu = Menu(go_Menu , tearoff=0)
sub_menu.add_command(label='Group 1', accelerator="Ctrl+1")
sub_menu.add_command(label='Group 2', accelerator="Ctrl+2")
sub_menu.add_command(label='Group 3', accelerator="Ctrl+3")
sub_menu.add_command(label='Group 4', accelerator="Ctrl+4")
sub_menu.add_command(label='Group 5', accelerator="Ctrl+5")
sub_menu.add_separator()
sub_menu.add_cascade(label='Next Group')
sub_menu.add_cascade(label='Previous Group')
sub_menu.add_separator()
sub_menu.add_command(label='Group Left', accelerator="Ctrl+K Ctrl+LeftArrow")
sub_menu.add_command(label='Group Right', accelerator="Ctrl+K Ctrl+RightArrow")
sub_menu.add_command(label='Group Above', accelerator="Ctrl+K Ctrl+UpArrow")
sub_menu.add_command(label='Group Below', accelerator="Ctrl+K Ctrl+DownArrow")


go_Menu.add_cascade(label="Switch Group", menu = sub_menu)
go_Menu.add_separator()
go_Menu.add_command(label="Go to File...", accelerator="Ctrl+P")
go_Menu.add_command(label="Go to Symbol in Workspace...", accelerator="Ctrl+T")
go_Menu.add_separator()
go_Menu.add_command(label="Go to Symbol in Editor...", accelerator="Ctrl+Shift+O")
go_Menu.add_command(label="Go to Definition", accelerator="F12")
go_Menu.add_command(label="Go to Declaration")
go_Menu.add_command(label="Go to Type Definition")
go_Menu.add_command(label="Go to Implementations", accelerator="Ctrl+F12")
go_Menu.add_command(label="Go to References", accelerator="Shift+F12")
go_Menu.add_separator()
go_Menu.add_command(label="Go to Line/Column...", accelerator="Ctrl+G")
go_Menu.add_command(label="Go to Bracket", accelerator="Ctrl+Shift+\ ")
go_Menu.add_separator()
go_Menu.add_command(label="Next Problem", accelerator="F8")
go_Menu.add_command(label="Previous Problem", accelerator="Shift+F8")
go_Menu.add_separator()
go_Menu.add_command(label="Next Change", accelerator="Alt+F3")
go_Menu.add_command(label="Previous Change", accelerator="Shift+Alt+F3")

# Run Menu
run_Menu = Menu(menuber, tearoff=0)
menuber.add_cascade(label='Run', menu=run_Menu, underline=0)
run_Menu.add_command(label="Start Debugging", accelerator="F5")
run_Menu.add_command(label="Run Without Debugging", accelerator="Ctrl+F5")
run_Menu.add_command(label="Stop Debugging", accelerator="Shift+F5")
run_Menu.add_command(label="Restart Debugging", accelerator="Ctrl+Shift+F5")
run_Menu.add_separator()
run_Menu.add_command(label="Open Configurations")
run_Menu.add_command(label="Add Configuration...")
run_Menu.add_separator()
run_Menu.add_command(label="Step Over", accelerator="F10")
run_Menu.add_command(label="Step into", accelerator="F11")
run_Menu.add_command(label="Step Out", accelerator="Shift+F11")
run_Menu.add_command(label="Continue", accelerator="F5")
run_Menu.add_separator()
run_Menu.add_command(label="Toggle Breakpoint", accelerator="F9")

sub_menu = Menu(run_Menu , tearoff=0)
sub_menu.add_cascade(label='Conditional Breakpoint...')
sub_menu.add_cascade(label='Edit Breakpoint')
sub_menu.add_command(label='Inline Breakpoint',accelerator="Stift+F9")
sub_menu.add_cascade(label='Function Breakpoint...')
sub_menu.add_cascade(label='Logpoint...')
sub_menu.add_cascade(label='Triggered Breakpoint...')
 
run_Menu.add_cascade(label="New Breakpoint" , menu = sub_menu)
run_Menu.add_separator()
run_Menu.add_command(label="Enable All Breakpoints")
run_Menu.add_command(label="Disable All Breakpoints")
run_Menu.add_command(label="Remove All Breakpoints")
run_Menu.add_separator()
run_Menu.add_command(label="Install Additional Debuggers...")

# Terminal Menu
terminal_Menu = Menu(menuber, tearoff=0)
menuber.add_cascade(label='Terminal', menu=terminal_Menu, underline=0)
terminal_Menu.add_command(label="New Terminal", accelerator="Ctrl+Shift+`")
terminal_Menu.add_command(label="Split Terminal", accelerator="Ctrl+Shift+5")
terminal_Menu.add_separator()
terminal_Menu.add_command(label="Run Task...")
terminal_Menu.add_command(label="Run Build Task...", accelerator="Ctrl+Shift+B")
terminal_Menu.add_command(label="Run Active File")
terminal_Menu.add_command(label="Run Selected Text")
terminal_Menu.add_separator()
terminal_Menu.add_command(label="Show Running Tasks...")
terminal_Menu.add_command(label="Restart Running Task...")
terminal_Menu.add_command(label="Terminate Task...")
terminal_Menu.add_separator()
terminal_Menu.add_command(label="Configure Tasks...")
terminal_Menu.add_command(label="Configure Default Build Task...")

# Help Menu
help_Menu = Menu(menuber, tearoff=0)
menuber.add_cascade(label='Help', menu=help_Menu, underline=0)
help_Menu.add_command(label="Welcome")
help_Menu.add_command(label="Show All Commands", accelerator="Ctrl+Shift+P")
help_Menu.add_command(label="Documentation")
help_Menu.add_command(label="Editor Playground")
help_Menu.add_command(label="Show Release Notes")
help_Menu.add_command(label="Get Started with Accessibility Features")
help_Menu.add_separator()
help_Menu.add_command(label="Keyboard Shortcuts Reference", accelerator="Ctrl+K Ctrl+R")
help_Menu.add_command(label="Video Tutorials")
help_Menu.add_command(label="Tips and Tricks")
help_Menu.add_separator()
help_Menu.add_command(label="Join Us on YouTube")
help_Menu.add_command(label="Search Feature Requests")
help_Menu.add_command(label="Report Issue")
help_Menu.add_separator()
help_Menu.add_command(label="View License")
help_Menu.add_command(label="Privacy Statement")
help_Menu.add_separator()
help_Menu.add_command(label="Toggle Developer Tools ")
help_Menu.add_command(label="Open Process Explorer")
help_Menu.add_separator()
help_Menu.add_command(label="Restart to Update")
help_Menu.add_separator()
help_Menu.add_command(label="About")

# Run main loop
window.mainloop()
